### ISSUE TITLE
Sidepanel for administratives task not visible when loaded while already logged in

### ISSUE THREAD

**Issue by cwittern** [eXist-db/dashboard#129]
> To be able to better understand you problem, please add as much information as possible to this ticket. Always test your bugs against the latest stable release of exist. We cannot provide support for older versions here on GitHub. If the version of eXist that is experiencing the issue is more than 1 major version behind the most recent release, please consider posting a question on our mailing list. 

This is happening on a Ubuntu 19.10 system with eXist 5.2.0 in Firefox.

**Describe the bug**
If an administrative already is logged in and loads the dashboard, the sidepanel is not visible and there is no way to make it visible short of logging out and in again.  When I came to the new dashboard for the first time, I happened to be in that situation and did not even know that a sidepanel exists.

**Expected behavior**

In this situation (dba user already logged in in active session) I would expect the sidepanel to be immediately visible.  If this is not possible, there should be a button to make it visible 

**To Reproduce**

Log into a database instance with a dba user.  Open a different tab.

**Comment by JoernT** [comment]
this is fixed now as long as you're logged in with the same browser. On a different browser you'll need to login anyway.

**Comment by joewiz** [comment]
As discussed in the Community Call, users are still seeing this problem with the current releases of eXist.

I will try to post steps to reproduce and more specific info.

**Comment by joewiz** [comment]
Steps to reproduce:

1. Log into Dashboard as the admin user. You will see the left sidebar pane indicating successful dba login.
2. Quit and restart eXist.
3. Reload the Dashboard page. The admin user is logged out, as expected.
4. Repeat step 1. The admin user's credentials are accepted, but the sidebar does not re-appear.

The only ways to escape this trap are: (1) Delete the `org.exist.login` cookie and perform step 1 again, or (2) Log into eXide with the "remember me for 2 weeks" checkbox checked and reload the Dashboard page (without explicitly logging into Dashboard again). (If the "remember me for 2 weeks" checkbox is not checked, the login to eXide is successful but the session is not "shared" with Dashboard.)

In contrast, when performing the analogous steps 1-4 with eXide, step 4 results in a successful login.
